import assert from 'node:assert/strict';import {id,hash,clone,canonical} from '../public/domain.mjs';import {setup,input} from './helpers.mjs';
export function boundarySuite(test,make){
 const scenario=(name,fn)=>test(name,async()=>{const {service,close}=make();try{await fn(service);}finally{close?.();}});
 scenario('accept idempotent after current changes: 8 concurrent retries',async service=>{const c=await setup(service);await service.command(c.team.id,c.backup,c.umpireToken);const replies=await Promise.all(Array.from({length:8},()=>service.command(c.team.id,c.accept,c.umpireToken)));assert(replies.every(x=>x.outcome.state==='accepted'));const t=await service.get(c.team.id);assert.deepEqual(t.score,[1,0]);assert.equal(t.currentId,'m2');assert.equal(t.generation,2);});
 scenario('Team Undo then retry: accepted_then_undone, no second effect',async service=>{const c=await setup(service);await service.command(c.team.id,c.backup,c.umpireToken);const a=await service.command(c.team.id,c.accept,c.umpireToken);const undo={id:id(),type:'undo',expectedResultId:a.outcome.acceptedResultId,expectedRevision:a.team.revision};await service.command(c.team.id,undo,c.adminToken);await service.command(c.team.id,undo,c.adminToken);const replay=await service.command(c.team.id,c.accept,c.umpireToken);assert.equal(replay.outcome.state,'accepted_then_undone');assert.deepEqual(replay.team.score,[0,0]);assert.equal(replay.team.currentId,'m1');assert.equal(replay.team.generation,3);});
 scenario('same command ID changed payload rejected',async service=>{const c=await setup(service);await service.command(c.team.id,c.backup,c.umpireToken);await service.command(c.team.id,c.accept,c.umpireToken);await assert.rejects(()=>service.command(c.team.id,{...c.accept,envelopeHash:'wrong'},c.umpireToken),/Другой пакет/);});
 scenario('manual and automatic race has exactly one winner',async service=>{const c=await setup(service);await service.command(c.team.id,c.backup,c.umpireToken);const both=await Promise.allSettled([service.command(c.team.id,c.accept,c.umpireToken),service.command(c.team.id,{id:id(),type:'manual',generation:1,individualMatchId:'m1',result:{gamesA:0,gamesB:2}},c.adminToken)]);assert.equal(both.filter(x=>x.status==='fulfilled').length,1);assert.equal((await service.get(c.team.id)).score.reduce((a,b)=>a+b),1);});
 scenario('revoked generation rejects stale report and Live',async service=>{const c=await setup(service);await service.command(c.team.id,{id:id(),type:'revoke',generation:1},c.adminToken);await assert.rejects(()=>service.command(c.team.id,c.backup,c.umpireToken),/отозван/);await assert.rejects(()=>service.command(c.team.id,{id:id(),type:'live',binding:c.session.binding,localRevision:1,view:{}},c.umpireToken),/отозван/);});
 scenario('writer cannot steal registration; retry preserves epochs',async service=>{const c=await setup(service);const r=await service.command(c.team.id,c.reg,c.umpireToken);assert.equal(r.outcome.binding.attemptEpoch,1);await assert.rejects(()=>service.command(c.team.id,{...c.reg,id:id(),attemptId:id(),writerId:'other'},c.umpireToken),/другой счётчик/);});
 scenario('forged hash and rehashed fraudulent report rejected',async service=>{const c=await setup(service);const bad=clone(c.backup);bad.id=id();bad.envelope.result.gamesA=1;await assert.rejects(()=>service.command(c.team.id,bad,c.umpireToken),/Хеш/);const forged=clone(c.backup);forged.id=id();const r=JSON.parse(forged.envelope.reportBytes);r.result.gamesA=1;forged.envelope.result.gamesA=1;forged.envelope.reportBytes=canonical(r);forged.envelope.reportHash=await hash(forged.envelope.reportBytes);const {payloadHash,...base}=forged.envelope;forged.envelope.payloadHash=await hash(base);await assert.rejects(()=>service.command(c.team.id,forged,c.umpireToken),/Итог/);});
 scenario('accept without immutable backup rejected',async service=>{const c=await setup(service);await assert.rejects(()=>service.command(c.team.id,c.accept,c.umpireToken),/Нет подтверждённого/);});
 scenario('wrong role and wrong Team capabilities rejected',async service=>{const c=await setup(service),other=await service.create(input());for(const token of ['',other.adminToken,c.adminToken])await assert.rejects(()=>service.command(c.team.id,c.backup,token),e=>e.code==='forbidden');await assert.rejects(()=>service.command(c.team.id,{id:id(),type:'revoke',generation:1},c.umpireToken),e=>e.code==='forbidden');});
 scenario('manual no report: 2:2 final draw and Undo reopens',async service=>{const c=await service.create(input());let t=c.team,last;for(let i=0;i<4;i++){last=await service.command(t.id,{id:id(),type:'manual',generation:t.generation,individualMatchId:t.currentId,result:i%2?{gamesA:0,gamesB:2}:{gamesA:2,gamesB:0}},c.adminToken);t=last.team;}assert.equal(t.currentId,null);assert.deepEqual(t.score,[2,2]);const u=await service.command(t.id,{id:id(),type:'undo',expectedResultId:last.outcome.acceptedResultId,expectedRevision:t.revision},c.adminToken);assert.equal(u.team.currentId,'m4');assert.deepEqual(u.team.score,[2,1]);});
 scenario('public view contains no capability hashes, receipts or report bytes',async service=>{const c=await setup(service);await service.command(c.team.id,c.backup,c.umpireToken);const t=await service.get(c.team.id);assert(!('adminHash'in t));assert(!('receipts'in t));assert(!('reports'in t));});
}
