import assert from 'node:assert/strict';
import {writeFile,mkdir,readFile} from 'node:fs/promises';import http from 'node:http';
import {startServer} from '../server/http.mjs';import {SqliteRepository} from '../server/repository.mjs';
const {chromium}=await import(process.env.TTS_PLAYWRIGHT||'playwright');
await mkdir('evidence',{recursive:true});const results=[];const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const note=(mode,scenario)=>{results.push({mode,scenario,status:'PASS'});console.log('PASS',mode,scenario);};
try{for(const mode of ['server','demo']){
 let srv;if(mode==='server')srv=startServer({port:0,repo:new SqliteRepository(':memory:')});else{srv=http.createServer(async(req,res)=>{try{const name=req.url.split('?')[0],f=new URL('../public/'+(name==='/'?'index.html':name.slice(1)),import.meta.url);res.setHeader('Content-Type',f.pathname.endsWith('.mjs')?'text/javascript':f.pathname.endsWith('.css')?'text/css':'text/html');res.end(await readFile(f));}catch{res.statusCode=404;res.end();}});srv.listen(0,'127.0.0.1');}
 await new Promise(r=>srv.listening?r():srv.once('listening',r));const base='http://127.0.0.1:'+srv.address().port;
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];ctx.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.waitForFunction=async fn=>{const end=Date.now()+20000;while(Date.now()<end){if(await p.evaluate(fn))return;await new Promise(r=>setTimeout(r,80));}throw new Error('Condition timeout: '+fn);};});
 try{
 const a=await ctx.newPage();await a.goto(base);await a.locator('#create').waitFor();await a.getByRole('button',{name:'Создать встречу',exact:true}).click();await a.waitForURL(/team=/);await a.locator('#manual').waitFor();const tid=new URL(a.url()).searchParams.get('team');note(mode,'Create via UI');
 const u=await ctx.newPage(),v=await ctx.newPage();await u.goto(base+'/?team='+tid+'&role=umpire');await v.goto(base+'/?team='+tid+'&role=viewer');await u.locator('#prepare').click();await u.locator('[data-cmd="arrived"]').waitFor();await v.waitForFunction(()=>document.body.innerText.includes('Ожидание спортсменов'));assert.deepEqual(await u.locator('.digits').allTextContents(),['\u00a0','\u00a0']);note(mode,'Prepared phase visible; blank distinct from zero');
 await u.locator('[data-cmd="arrived"]').click();await u.locator('[data-cmd="start"]').click();await u.waitForFunction(()=>document.querySelector('.digits')?.textContent==='0');
 await u.locator('#diagnostics summary').click();await u.locator('#fail-save').click();await u.locator('[data-point="0"]').click();await u.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('не сохранена'));assert.equal(await u.locator('.digits').first().innerText(),'0');note(mode,'Failed commit does not advance score');
 await u.locator('[data-point="0"]').click();await u.waitForFunction(()=>document.querySelector('.digits')?.textContent==='1');await u.reload();await u.locator('[data-cmd="undo"]').click();await u.waitForFunction(()=>document.querySelector('.digits')?.textContent==='0');note(mode,'Reload restores one Undo');
 await u.locator('#diagnostics summary').click();await u.locator('#offline').check();await u.locator('[data-point="0"]').click();await u.waitForFunction(()=>document.querySelector('.digits')?.textContent==='1');await u.locator('#offline').uncheck();await v.waitForFunction(()=>document.querySelector('.digits')?.textContent==='1');note(mode,'Offline local score and reconnect');
 for(let i=1;i<11;i++)await u.locator('[data-point="0"]').click();await u.locator('[data-cmd="next"]').click();await u.locator('[data-cmd="start"]').click();for(let i=0;i<11;i++)await u.locator('[data-point="0"]').click();await u.locator('#complete').waitFor();assert.deepEqual(await u.locator('.sets').allTextContents(),['0','1']);note(mode,'Held final for actual 2:0');
 await u.locator('#fail-save').click();await u.locator('#complete').click();await u.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('не сохранена'));assert.equal(await a.locator('.team-score').innerText(),'0 : 0');assert(await u.locator('#complete').isEnabled());note(mode,'Completion commit failure sends no result');
 await u.locator('#drop-ack').click();await u.locator('#complete').click();await u.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('потеряно'));await a.waitForFunction(()=>document.querySelector('.team-score')?.textContent==='1 : 0');await u.locator('#retry').click();await u.waitForFunction(()=>document.body.innerText.includes('Предыдущий результат: принят'));note(mode,'Lost acceptance response; retry gives one win');
 await a.locator('#team-undo').click();await a.waitForFunction(()=>document.querySelector('.team-score')?.textContent==='0 : 0');await u.locator('#retry').click();await u.waitForFunction(()=>document.body.innerText.includes('Предыдущий результат: отменён'));assert.equal(await a.locator('.team-score').innerText(),'0 : 0');note(mode,'Undo then stale retry never restores result');
 await u.locator('#prepare').click();await u.locator('[data-cmd="arrived"]').waitFor();await v.waitForFunction(()=>document.body.innerText.includes('Ожидание спортсменов'));assert.deepEqual(await v.locator('.digits').allTextContents(),['\u00a0','\u00a0']);note(mode,'New attempt blank, no previous score');
 const blocked=await ctx.newPage();await blocked.goto(base+'/?team='+tid+'&role=umpire');await blocked.getByText('Управление уже открыто',{exact:true}).waitFor();await blocked.close();note(mode,'Second writer blocked');
 for(const width of [390,768]){await u.setViewportSize({width,height:1000});assert(await u.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await u.screenshot({path:`evidence/${mode}-${width}.png`,fullPage:true});}note(mode,'390px and 768px without horizontal overflow');assert.deepEqual(errors,[]);note(mode,'No browser page errors');
 await u.close();const cross=await ctx.newPage();await cross.goto(base+'/?team=00000000-0000-4000-8000-000000000001&role=umpire');await cross.getByText('Другая роль уже управляет другой командной встречей.',{exact:true}).waitFor();note(mode,'Different Team blocked while Administrator active');await cross.close();
 }finally{await ctx.close();await new Promise(r=>srv.close(r));}
}}finally{await browser.close();await writeFile('evidence/browser.json',JSON.stringify({browser:'Chromium 134.0.6998.35',results},null,2));}
console.log('TOTAL',results.length);
