import test from 'node:test';import assert from 'node:assert/strict';
import {createTeam,publicTeam} from '../public/authority.mjs';
import {makeSession,counterCommand,counterView,result,points,server,freezeCompletion,validateReport,canonical,id} from '../public/domain.mjs';import {input,command,winGame} from './helpers.mjs';
async function fresh(bestOf=3){const c=await createTeam({...input(),bestOf});return makeSession(publicTeam(c.state),{writerId:'w'});}
test('seven phases, blank versus zero, held final and release',async()=>{let s=await fresh();assert.equal(counterView(s).gamePoints,null);assert.equal(counterView(s).gamesWon,null);s=command(s,'arrived');assert.deepEqual(counterView(s).gamesWon,[0,0]);assert.equal(counterView(s).gamePoints,null);s=winGame(s,0);assert.equal(s.phase,'game_break');assert.deepEqual(counterView(s).gamesWon,[0,0]);s=command(s,'next');assert.equal(s.phase,'prepare_next_game');assert.equal(counterView(s).gamePoints,null);s=winGame(s,0);assert.equal(s.phase,'match_over');assert.deepEqual(counterView(s).gamesWon,[1,0]);assert.equal(result(s).gamesA,2);s=command(s,'release');assert.equal(counterView(s).gamePoints,null);assert.equal(result(s).gamesA,2);});
test('deciding 12:10: sport 3:2, displayed 2:2',async()=>{let s=command(await fresh(5),'arrived');for(const side of [0,1,0,1]){s=winGame(s,side);s=command(s,'next');}s=command(s,'start');for(let i=0;i<10;i++){s=command(s,'point',{side:0});s=command(s,'point',{side:1});}assert.equal(server(s),0);s=command(s,'point',{side:0});assert.equal(server(s),1);s=command(s,'point',{side:0});assert.deepEqual(counterView(s).gamePoints,[12,10]);assert.deepEqual(counterView(s).gamesWon,[2,2]);assert.deepEqual(result(s),{gamesA:3,gamesB:2,winner:0});});
test('Undo after final returns game with higher revision',async()=>{let s=command(await fresh(),'arrived');s=winGame(s,0);s=command(s,'next');s=winGame(s,0);const rev=s.localRevision;s=command(s,'undo');assert.equal(s.phase,'game');assert.equal(s.localRevision,rev+1);assert.equal(result(s),null);assert.deepEqual(points(s.games.at(-1)),[10,0]);});
test('deduplication and phase guards',async()=>{let s=command(await fresh(),'arrived');s=command(s,'start');assert.throws(()=>command(s,'start'));const cmd={id:id(),type:'point',side:1},once=counterCommand(s,cmd);assert.equal(canonical(counterCommand(once,cmd)),canonical(once));});
test('frozen bytes survive release; sporting undo closed',async()=>{let s=command(await fresh(),'arrived');s=winGame(s,0);s=command(s,'next');s=winGame(s,0);await assert.rejects(()=>freezeCompletion(s));s.binding={attemptId:s.attemptId};s=await freezeCompletion(s);const bytes=canonical(s.completion);s=command(s,'release');assert.equal(canonical(s.completion),bytes);assert.throws(()=>command(s,'undo'));});
test('report rejects extra rally and fraudulent result',async()=>{let s=command(await fresh(),'arrived');s=winGame(s,0);s=command(s,'next');s=winGame(s,0);s.binding={attemptId:s.attemptId};s=await freezeCompletion(s);const r=JSON.parse(s.completion.reportBytes);r.games[0].rallies.push(0);assert.throws(()=>validateReport(r));const r2=JSON.parse(s.completion.reportBytes);r2.result.gamesA=1;assert.throws(()=>validateReport(r2));});
